'use client';
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ChevronLeft, ChevronRight, Maximize, Send } from 'lucide-react';
import { useParams, useRouter } from 'next/navigation';
import { DashboardShell } from '@/components/dashboard/dashboard-shell';

type Question={id:string;prompt:string;type:string;options:string[]};
type Test={id:string;title:string;duration_minutes:number;passing_score:number};

export default function TestPage(){
  const params=useParams<{id:string}>();
  const router=useRouter();
  const [test,setTest]=useState<Test|null>(null); const [questions,setQuestions]=useState<Question[]>([]); const [answers,setAnswers]=useState<Record<string,unknown>>({});
  const [attemptId,setAttemptId]=useState(''); const [step,setStep]=useState(0); const [time,setTime]=useState(0); const [message,setMessage]=useState('Loading assessment...'); const [busy,setBusy]=useState(false); const [events,setEvents]=useState<string[]>([]); const startedRef=useRef(false);
  useEffect(()=>{let cancelled=false; async function load(){const response=await fetch(`/api/tests?id=${params.id}`);const data=await response.json();if(!response.ok){setMessage(data.error||'Unable to load assessment.');return;}setTest(data.test);setQuestions(data.questions??[]);setTime(data.test.duration_minutes*60);const start=await fetch('/api/tests',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'start',testId:params.id})});const started=await start.json();if(cancelled)return;if(!start.ok){setMessage(started.error||'Unable to start assessment.');return;}setAttemptId(started.attempt.id);setMessage('');startedRef.current=true;}load();return()=>{cancelled=true}},[params.id]);
  useEffect(()=>{if(!attemptId)return;const timer=setInterval(()=>setTime(value=>{if(value<=1){clearInterval(timer);return 0;}return value-1}),1000);const save=setInterval(()=>{void fetch('/api/tests',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'save',testId:params.id,attemptId,answers,suspiciousEvents:events})})},10000);const onVisibility=()=>{if(document.hidden)setEvents(prev=>[...prev,'tab_hidden'].slice(-50));};document.addEventListener('visibilitychange',onVisibility);return()=>{clearInterval(timer);clearInterval(save);document.removeEventListener('visibilitychange',onVisibility)}},[attemptId,params.id,answers,events]);
  useEffect(()=>{ if(time===0 && attemptId && !busy && startedRef.current){ void submit(); } },[time,attemptId,busy]);

  async function fullscreen(){try{await document.documentElement.requestFullscreen()}catch{setMessage('Fullscreen is not available in this browser.')}}
  useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&['c','v','x'].includes(event.key.toLowerCase())){event.preventDefault();setEvents(prev=>[...prev,'clipboard_attempt'].slice(-50));}};document.addEventListener('keydown',onKey);return()=>document.removeEventListener('keydown',onKey)},[]);
    useEffect(()=>{const onExitClick=(event:MouseEvent)=>{const target=event.target as HTMLElement;const link=target.closest('a[href="/dashboard/tests"]');if(!link)return;if(!window.confirm('Are you sure you want to exit this test? Your current attempt will not be submitted.'))event.preventDefault();};document.addEventListener('click',onExitClick);return()=>document.removeEventListener('click',onExitClick)},[]);
  async function submit(){setBusy(true);const response=await fetch('/api/tests',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'submit',testId:params.id,attemptId,answers,suspiciousEvents:events})});const data=await response.json();if(!response.ok)setMessage(data.error||'Unable to submit.');else router.replace(`/tests/${params.id}/result?attemptId=${encodeURIComponent(data.attemptId)}`);setBusy(false)}
  if(!test)return <DashboardShell><div className="test-blocked-state surface card"><div className="eyebrow">Assessment</div><h1 className="title" style={{fontSize:30}}>Assessment unavailable</h1><p className="subtitle">{message}</p>{message.toLowerCase().includes('complete') ? <Link className="btn primary small" href="/dashboard/courses">Continue course learning</Link> : <Link className="btn secondary small" href="/dashboard/tests">Back to tests</Link>}</div></DashboardShell>;
  const question=questions[step];const minutes=String(Math.floor(time/60)).padStart(2,'0');const seconds=String(time%60).padStart(2,'0');
  function exitTest(){if(window.confirm('Are you sure you want to exit this test? Your current attempt will not be submitted.')) router.replace('/dashboard/tests');}
    return <main className="page test-page"><div className="container test-container"><div className="breadcrumbs"><Link href="/dashboard/tests"><ArrowLeft size={14}/> Tests</Link> / {test.title}</div><div className="test-heading"><div><div className="eyebrow">Assessment</div><h1 className="title">{test.title}</h1><p className="subtitle">{questions.length} questions <span>·</span> pass mark {test.passing_score}%</p></div><div className="test-heading-actions"><button className="btn secondary small" onClick={fullscreen}><Maximize size={13}/> Focus mode</button><div className="test-timer"><div>Time left</div><strong>{minutes}:{seconds}</strong></div></div></div><div className="test-progress-track"><span style={{width:`${questions.length?((step+1)/questions.length)*100:0}%`}} /></div><div className="surface card test-question-card">{question?<><div className="test-question-meta"><span className="chip active">Question {step+1} of {questions.length}</span><span>{Math.round(((step+1)/questions.length)*100)}% complete</span></div><h2>{question.prompt}</h2><div className="test-options">{question.options?.map((option,index)=><button key={option} type="button" onClick={()=>setAnswers(current=>({...current,[question.id]:option}))} className={`test-option ${answers[question.id]===option?'selected':''}`}><span className="test-option-key">{String.fromCharCode(65+index)}</span><span>{option}</span><span className="test-option-radio">{answers[question.id]===option?'●':'○'}</span></button>)}</div><div className="bottom-nav test-navigation"><button className="btn secondary small" disabled={step===0} onClick={()=>setStep(value=>value-1)}><ChevronLeft size={14}/> Previous</button>{step<questions.length-1?<button className="btn primary small" onClick={()=>setStep(value=>value+1)}>Next <ChevronRight size={14}/></button>:<button className="btn primary small" onClick={submit} disabled={busy}><Send size={14}/> {busy?'Submitting...':'Submit assessment'}</button>}</div></>:<div className="empty">No questions have been assigned to this assessment.</div>}{message&&<div className="notice" style={{marginTop:12}}>{message}</div>}</div></div></main>;
}
